export const SAVE_GARAGE = 'SAVE_GARAGE';
export const REMOVE_GARAGE = 'REMOVE_GARAGE';
export const ADD_GARAGE = 'ADD_GARAGE';
export const GET_GARAGE_LIST = 'GET_GARAGE_LIST';
export const SAVE_SUPPLIER = 'SAVE_SUPPLIER';
export const REMOVE_SUPPLIER = 'REMOVE_SUPPLIER';
export const ADD_SUPPLIER = 'ADD_SUPPLIER';

export const REQUEST_UPDATE_ORDER = 'REQUEST_UPDATE_ORDER'
export const RECEIVE_UPDATE_ORDER = 'RECEIVE_UPDATE_ORDER'
export const FAILED_UPDATE_ORDER = 'FAILED_UPDATE_ORDER'
export const REQUEST_UPDATE_PART = 'REQUEST_UPDATE_PART'
export const RECEIVE_UPDATE_PART = 'RECEIVE_UPDATE_PART'
export const FAILED_UPDATE_PART = 'FAILED_UPDATE_PART'

export const REQUEST_GARAGE_LIST = 'REQUEST_GARAGE_LIST'
export const RECEIVE_GARAGE_LIST = 'RECEIVE_GARAGE_LIST'
export const FETCH_GARAGELIST_FAILED = 'FETCH_GARAGELIST_FAILED'
export const REQUEST_UPDATE_GARAGE = 'REQUEST_UPDATE_GARAGE'
export const RECEIVE_UPDATE_GARAGE = 'RECEIVE_UPDATE_GARAGE'
export const FAILED_UPDATE_GARAGE = 'FAILED_UPDATE_GARAGE'

export const REQUEST_SUPPLIER_LIST = 'REQUEST_SUPPLIER_LIST'
export const RECEIVE_SUPPLIER_LIST = 'RECEIVE_SUPPLIER_LIST'
export const FAILED_FETCH_SUPPLIER_LIST = 'FAILED_FETCH_SUPPLIER_LIST'
export const REQUEST_UPDATE_SUPPLIER = 'REQUEST_UPDATE_SUPPLIER'
export const RECEIVE_UPDATE_SUPPLIER = 'RECEIVE_UPDATE_SUPPLIER'
export const FAILED_UPDATE_SUPPLIER = 'FAILED_UPDATE_SUPPLIER'

export const REQUEST_ORDER_LIST = 'REQUEST_ORDER_LIST'
export const RECEIVE_ORDER_LIST = 'RECEIVE_ORDER_LIST'
export const FAILED_FETCH_ORDER_LIST = 'FAILED_FETCH_ORDER_LIST'

export const REQUEST_PART_LIST = 'REQUEST_PART_LIST'
export const RECEIVE_PART_LIST = 'RECEIVE_PART_LIST'
export const FAILED_FETCH_PART_LIST = 'FAILED_FETCH_PART_LIST'

export const REQUEST_CARMAKE_LIST = 'REQUEST_CARMAKE_LIST'
export const RECEIVE_CARMAKE_LIST = 'RECEIVE_CARMAKE_LIST'
export const FAILED_FETCH_CARMAKE_LIST = 'FAILED_FETCH_CARMAKE_LIST'

export const REQUEST_SAVE_CARMAKE = 'REQUEST_SAVE_CARMAKE'
export const RECEIVE_SAVE_CARMAKE = 'RECEIVE_SAVE_CARMAKE'
export const FAILED_SAVE_CARMAKE = 'FAILED_SAVE_CARMAKE'
